services:
  worker:
    image: demo-worker:latest
    build: worker
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 5
  
  server:
    image: demo-server:latest
    build: server
    restart: unless-stopped
    depends_on:
      - worker